// crates/msk144plus_packjt/src/callsign.rs
//
// 28-bit callsign codec. Ported from WSJT-X packjt77.f90 unpack28/pack28.
//
// Number ranges:
//   0          = "DE"
//   1          = "QRZ"
//   2          = "CQ"
//   3..=1002   = "CQ_000" .. "CQ_999"   (NNN suffix, decimal)
//   1003..=532443 = "CQ_AAAA"           (4-letter suffix, base-27)
//   532444..=2063592 - 1 = unused token range (ungenerated by encoder)
//   2063592..=2063592+4194304-1 = 22-bit hash of nonstandard call (decode -> "<...>")
//   2063592+4194304..  = standard 6-character call (positional encode)
//
// Constants:
//   NTOKENS = 2063592
//   MAX22   = 4194304 = 2^22

const NTOKENS: u32 = 2_063_592;
const MAX22: u32 = 4_194_304; // 2^22

// Alphabets used in the standard-call positional encoding:
//   c1: position 1 (optional letter or empty)        - 37 chars
//   c2: position 2 (letter or digit, mandatory)      - 36 chars
//   c3: position 3 (digit, the "number")             - 10 chars
//   c4: positions 4-6 (optional suffix letters)      - 27 chars
const C1: &[u8] = b" 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const C2: &[u8] = b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const C3: &[u8] = b"0123456789";
const C4: &[u8] = b" ABCDEFGHIJKLMNOPQRSTUVWXYZ";

/// What kind of callsign field we just decoded.
#[derive(Debug, Clone, PartialEq)]
pub enum Call {
    /// "DE"
    De,
    /// "QRZ"
    Qrz,
    /// "CQ" (no suffix)
    Cq,
    /// "CQ NNN" with a 3-digit numeric suffix.
    CqNum(u16),
    /// "CQ XXXX" with a 1-4 letter suffix.
    CqLetters(String),
    /// 22-bit hash of a nonstandard callsign. Resolved to "<...>" until a
    /// hash table is plumbed in.
    Hash22(u32),
    /// A standard amateur callsign like "K1ABC", "VP8/G3WGN", or "GW4WND".
    Standard(String),
    /// Decoder failed - reserved for malformed inputs.
    Invalid,
}

impl Call {
    /// Render this call to the text representation WSJT-X uses on the wire.
    /// Note that "CQ_NNN"/"CQ_AAAA" appear with an underscore here; the
    /// caller (the message formatter) replaces the underscore with a space
    /// when composing the final display text.
    pub fn to_wire_text(&self) -> String {
        match self {
            Call::De => "DE".into(),
            Call::Qrz => "QRZ".into(),
            Call::Cq => "CQ".into(),
            Call::CqNum(n) => format!("CQ_{:03}", n),
            Call::CqLetters(s) => format!("CQ_{}", s),
            Call::Hash22(_) => "<...>".into(),
            Call::Standard(s) => s.clone(),
            Call::Invalid => "QU1RK".into(),
        }
    }
}

/// Decode a 28-bit callsign field.
pub fn unpack28(n28: u32) -> Call {
    // Special tokens first
    if n28 < NTOKENS {
        if n28 == 0 { return Call::De; }
        if n28 == 1 { return Call::Qrz; }
        if n28 == 2 { return Call::Cq; }
        if n28 <= 1002 {
            return Call::CqNum((n28 - 3) as u16);
        }
        if n28 <= 532_443 {
            // CQ_AAAA: 4-letter base-27 suffix starting at n28=1003
            let mut n = n28 - 1003;
            let i1 = n / (27 * 27 * 27); n -= i1 * 27 * 27 * 27;
            let i2 = n / (27 * 27);       n -= i2 * 27 * 27;
            let i3 = n / 27;
            let i4 = n - i3 * 27;
            let s: String = [i1, i2, i3, i4]
                .iter()
                .map(|&i| C4[i as usize] as char)
                .collect::<String>()
                .trim()
                .to_string();
            // If suffix trims to empty, this is the degenerate 1003 case
            // ("CQ" with no useful suffix). Tolerate by emitting empty.
            return Call::CqLetters(s);
        }
        // n28 in 532444..NTOKENS - this token range is unused by the
        // current encoder; treat as invalid for round-trip purposes.
        return Call::Invalid;
    }

    let n28 = n28 - NTOKENS;
    if n28 < MAX22 {
        return Call::Hash22(n28);
    }

    // Standard 6-character call: positional encode
    let mut n = n28 - MAX22;
    let i1 = n / (36 * 10 * 27 * 27 * 27); n -= i1 * 36 * 10 * 27 * 27 * 27;
    let i2 = n / (10 * 27 * 27 * 27);       n -= i2 * 10 * 27 * 27 * 27;
    let i3 = n / (27 * 27 * 27);            n -= i3 * 27 * 27 * 27;
    let i4 = n / (27 * 27);                  n -= i4 * 27 * 27;
    let i5 = n / 27;
    let i6 = n - i5 * 27;

    if (i1 as usize) >= C1.len()
        || (i2 as usize) >= C2.len()
        || (i3 as usize) >= C3.len()
        || (i4 as usize) >= C4.len()
        || (i5 as usize) >= C4.len()
        || (i6 as usize) >= C4.len()
    {
        return Call::Invalid;
    }

    let raw: String = [
        C1[i1 as usize], C2[i2 as usize], C3[i3 as usize],
        C4[i4 as usize], C4[i5 as usize], C4[i6 as usize],
    ]
    .iter()
    .map(|&b| b as char)
    .collect();

    let trimmed = raw.trim().to_string();
    if !is_valid_callsign(&trimmed) {
        return Call::Invalid;
    }
    Call::Standard(trimmed)
}

/// Encode a standard callsign into a 28-bit n28 value. Used by tests and
/// future TX support. Returns None if the callsign doesn't fit the
/// standard format (1-2 prefix chars + digit + 1-3 suffix chars).
pub fn pack28_standard(callsign: &str) -> Option<u32> {
    let cs = callsign.to_ascii_uppercase();
    if cs.len() > 6 || cs.is_empty() {
        return None;
    }
    // Pad to 6 chars positionally: detect the digit position and pad the
    // prefix to make the digit land at position 3 (1-indexed) = index 2.
    //
    // The digit may be at index 0 (e.g. "2W0XYZ" — UK 2-prefix), 1 (e.g.
    // "K1ABC" — US single-letter prefix), or 2 (e.g. "GW4WND" — UK two-
    // letter prefix). All three are standard-format calls and packable
    // via the C1/C2/C3 alphabets.
    let bytes: Vec<u8> = cs.bytes().collect();
    let dig_pos = bytes.iter().position(|b| b.is_ascii_digit())?;
    if dig_pos > 2 {
        return None;
    }
    // For dig_pos == 0 (digit at the very start, e.g. "2W0XYZ"), we have
    // no prefix letter, so position 0 stays as a space-pad and we shift
    // the rest right by 2. But the first-digit-of-the-callsign case (like
    // "2W0XYZ") needs the call to land such that position 1 holds the
    // digit prefix '2', position 2 holds the suffix character, etc.
    //
    // The Fortran does this via "pad_left = 2 - dig_pos" and lets dig_pos=0
    // produce pad_left=2 → callsign sits at indices 2..2+len. That matches
    // C1 (pos 0) = ' ', C2 (pos 1) = ' ', C3 (pos 2) = '2', etc — but C3
    // is digit-only and 2W0XYZ starts with '2' which IS a digit, so this
    // works for the form where the call is "2W0..." → padded to "  2W0..."
    // and read across C1,C2,C3,C4,C4,C4.
    //
    // Actually we need a different strategy for digit-first calls: pack them
    // so that the leading digit lands at position 2 (C3 alphabet which is
    // digit-only) and the W-letter prefix... hmm, that doesn't work either
    // because there's no prefix letter to put before the digit.
    //
    // WSJT-X handles digit-first callsigns ("2W0XYZ") by padding with a
    // leading space so the digit lands at index 2:
    //
    //   "2W0XYZ" (6 chars, dig_pos=0)
    //      → after pad: '  2W0XYZ'  (8 chars, too long)
    //
    // That's not feasible in 6 columns. So actual WSJT-X behaviour is:
    // detect 1-letter prefix (e.g. "K1ABC") OR digit-first prefix
    // ("2W0XYZ") and treat them differently. For the "2"-prefix case,
    // shift so digit is at position 2 and suffix follows:
    //
    //   "2W0XYZ" → "2W0XYZ" stays, but read C1='2', C2='W', C3='0', C4='X', C4='Y', C4='Z'
    //
    // C1 includes digits, so "2" is fine in C1. C3 must be the digit "0" — fine.
    // The "W" sits in C2 which accepts letters. So for digit-first callsigns,
    // pad_left = 0 and the digit-position-3 invariant becomes "the second
    // digit lands at position 2" — there's a digit at index 0 AND index 2.
    let pad = if dig_pos == 0 {
        // Digit at start: keep as-is; the SECOND digit (or rather, the
        // single digit between prefix and suffix) should land at index 2.
        // For "2W0XYZ", index 2 is '0' which is a digit. Good.
        // But for "2X0Y" (4-char digit-first calls), we'd need different
        // padding. The WSJT-X invariant is: position 2 must be a digit.
        if bytes.len() < 3 || !bytes[2].is_ascii_digit() {
            return None;
        }
        0
    } else {
        2 - dig_pos
    };
    let mut padded = vec![b' '; 6];
    for (i, &b) in bytes.iter().enumerate() {
        let target = i + pad;
        if target >= 6 { return None; }
        padded[target] = b;
    }

    let i1 = C1.iter().position(|&c| c == padded[0])? as u32;
    let i2 = C2.iter().position(|&c| c == padded[1])? as u32;
    let i3 = C3.iter().position(|&c| c == padded[2])? as u32;
    let i4 = C4.iter().position(|&c| c == padded[3])? as u32;
    let i5 = C4.iter().position(|&c| c == padded[4])? as u32;
    let i6 = C4.iter().position(|&c| c == padded[5])? as u32;

    let n = i1 * (36 * 10 * 27 * 27 * 27)
          + i2 * (10 * 27 * 27 * 27)
          + i3 * (27 * 27 * 27)
          + i4 * (27 * 27)
          + i5 * 27
          + i6;
    Some(n + MAX22 + NTOKENS)
}

/// Coarse callsign validity check used by the decoder to filter junk
/// outputs from the positional encoding. Mirrors the spirit of WSJT-X's
/// `callok()` predicate: must contain at least one letter and one digit,
/// and not have an embedded space.
fn is_valid_callsign(s: &str) -> bool {
    if s.is_empty() || s.len() > 6 { return false; }
    if s.contains(' ') { return false; }
    let has_letter = s.chars().any(|c| c.is_ascii_alphabetic());
    let has_digit = s.chars().any(|c| c.is_ascii_digit());
    has_letter && has_digit
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_decoding() {
        assert_eq!(unpack28(0), Call::De);
        assert_eq!(unpack28(1), Call::Qrz);
        assert_eq!(unpack28(2), Call::Cq);
        // CQ_000
        assert_eq!(unpack28(3), Call::CqNum(0));
        // CQ_123
        assert_eq!(unpack28(126), Call::CqNum(123));
        // CQ_999
        assert_eq!(unpack28(1002), Call::CqNum(999));
    }

    #[test]
    fn cq_letters() {
        // n28 = 1003 + 0*(27^3) + 0*(27^2) + 0*27 + 1 = 1004 -> "A"
        match unpack28(1004) {
            Call::CqLetters(s) => assert_eq!(s, "A"),
            other => panic!("expected CqLetters, got {:?}", other),
        }
    }

    #[test]
    fn standard_callsigns_round_trip() {
        for cs in ["K1ABC", "W9XYZ", "GW4WND", "VK2A", "AB1CD"] {
            let n = pack28_standard(cs).unwrap_or_else(|| panic!("pack {}", cs));
            match unpack28(n) {
                Call::Standard(decoded) => assert_eq!(decoded, cs, "round-trip {}", cs),
                other => panic!("decoding {}: got {:?}", cs, other),
            }
        }
    }

    #[test]
    fn standard_callsign_known_value() {
        // Verify the K1ABC encoding matches our hand-derivation:
        //   internal n = 3957069
        //   final n28 = 3957069 + MAX22 + NTOKENS = 10214965
        let n = pack28_standard("K1ABC").unwrap();
        assert_eq!(n, 10_214_965);
    }

    #[test]
    fn hash22_decoded_as_placeholder() {
        match unpack28(NTOKENS + 12345) {
            Call::Hash22(h) => assert_eq!(h, 12345),
            other => panic!("expected Hash22, got {:?}", other),
        }
    }

    #[test]
    fn callsign_validity() {
        assert!(is_valid_callsign("K1ABC"));
        assert!(is_valid_callsign("W9X"));
        assert!(!is_valid_callsign(""));
        assert!(!is_valid_callsign("ABCDEF"));   // no digit
        assert!(!is_valid_callsign("123456"));   // no letter
        assert!(!is_valid_callsign("K1 ABC"));   // embedded space
        assert!(!is_valid_callsign("TOOLONGCALLSIGN")); // > 6 chars
    }

    #[test]
    fn pack_digit_first_callsign() {
        // 2W0XYZ — UK 2-prefix Foundation/Intermediate licence callsigns.
        // Digit is at index 0; second digit at index 2.
        let n = pack28_standard("2W0XYZ").expect("2W0XYZ should pack");
        // Round-trip: unpack should give us back "2W0XYZ"
        let call = unpack28(n);
        match call {
            Call::Standard(s) => assert_eq!(s.trim(), "2W0XYZ"),
            other => panic!("expected Standard, got {:?}", other),
        }
    }

    #[test]
    fn pack_one_letter_prefix() {
        // K1ABC — US 1-letter prefix.
        let n = pack28_standard("K1ABC").expect("K1ABC should pack");
        let call = unpack28(n);
        match call {
            Call::Standard(s) => assert_eq!(s.trim(), "K1ABC"),
            other => panic!("expected Standard, got {:?}", other),
        }
    }

    #[test]
    fn pack_two_letter_prefix() {
        // GW4WND — UK 2-letter prefix.
        let n = pack28_standard("GW4WND").expect("GW4WND should pack");
        let call = unpack28(n);
        match call {
            Call::Standard(s) => assert_eq!(s.trim(), "GW4WND"),
            other => panic!("expected Standard, got {:?}", other),
        }
    }
}
